import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex ${inter.className}`}>
        <div className='w-[20%] flex flex-col gap-24 items-center py-12  bg-white px-8  min-h-screen'>
            <div className='h-52 w-52 bg-gray-300 rounded-full'></div>
            <div className='flex flex-col gap-4'>
                  <Link href="/">Home</Link>
                  <Link href="/gallery">Gallery</Link>
                  <Link href="/quiz">Quiz</Link>
            </div>
        </div>
        <div className='flex-1'>
          {children}
        </div>
      </body>
    </html>
  )
}
